trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
- task: SonarQubePrepare@5
  inputs:
    SonarQube: '.netcore'
    scannerMode: 'MSBuild'
    projectKey: 'TI-GCM-LABS_teste-react-native_AYHvENnYSS9Klg07_kU8'
    projectName: 'teste-react-native'
    - task: SonarQubeAnalyze@5